source 'https://rubygems.org'

gem 'activerecord', '~> 4.2.7.1', require: 'active_record'
gem 'bcrypt'
gem 'pry'
gem 'rack-test'
gem 'rake'
gem 'require_all'
gem 'rspec'
gem 'shotgun'
gem 'sinatra'
gem 'sinatra-activerecord', require: 'sinatra/activerecord'
gem 'sqlite3'
gem 'thin'
gem 'tux'
